version: '3.7'

services:
  backend:
    build:
      context: ./monolith-backend/backend
    command: gunicorn backend.wsgi --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
  frontend:
    build:
      context: ./monolith-ui
      dockerfile: Dockerfile
    volumes:
      - next_build:/next/out
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - next_build:/var/www/next
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

volumes:
  next_build:
  static_volume:
  media_volume:
