# Generated by Django 3.1.5 on 2021-02-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monolith_api', '0003_auto_20210216_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created',
            new_name='order_created',
        ),
    ]
