# Generated by Django 3.1.5 on 2021-02-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith_api', '0004_auto_20210217_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='lebron-dunk.jpg', upload_to='products/'),
        ),
    ]
